services:
  spark-notebook:
    build:
      context: ..
      dockerfile: docker/Dockerfile.jupyterspark
    container_name: projeto_bigdata
    volumes:
      - ..:/home/jovyan/app  # Mapeia o diretório atual para o diretório /app no container
    ports:
      - "8888:8888"  # Expor o Jupyter Notebook na porta 8888
    environment:
      - JUPYTER_ENABLE_LAB=yes